# Generated by Django 6.1 on 2026-09-13 12:29

import main.models
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Skill',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                ('percentage', models.IntegerField(default=0, validators=[main.models.validate_percentage])),
            ],
        ),
    ]
